# **1. PYTHON BASICS**

# *User Input*

In [22]:
name = input("Enter your name: ")

Enter your name:  Aamu


In [24]:
print("Hello", name)

Hello Aamu


# *Print Name and Age*

In [10]:
name = "Amoou"
age = 18

In [12]:
print("Name:", name)
print("Age:", age)

Name: Amoou
Age: 18


# *Basic Arithmetic*

In [15]:
a = 10
b = 3

In [19]:
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335


# *If-Else Condition*

In [27]:
marks = 75

In [29]:
if marks >= 60:
    print("Pass")
else:
    print("Fail")

Pass


# **LOOPS IN PYTHON**

# *For Loop*

In [33]:
print("FOR LOOP:")
for i in range(1, 6):
    print(i)

FOR LOOP:
1
2
3
4
5


# *While Loop*

In [38]:
print("WHILE LOOP:")
i = 1
while i <= 5:
    print(i)
    i += 1

WHILE LOOP:
1
2
3
4
5


# *Nested Loop*

In [41]:
print("NESTED LOOP:")
for i in range(1, 4):
    for j in range(1, 3):
        print(i, j)

NESTED LOOP:
1 1
1 2
2 1
2 2
3 1
3 2


# *Loop Using Break*

In [43]:
print("LOOP WITH BREAK:")
for i in range(1, 6):
    if i == 3:
        break
    print(i)

LOOP WITH BREAK:
1
2


# *Loop Using Continue*

In [48]:
print("LOOP WITH CONTINUE:")
for i in range(1, 6):
    if i == 3:
        continue
    print(i)

LOOP WITH CONTINUE:
1
2
4
5


# *Conditional Loop*

In [51]:
print("FOR LOOP WITH ELSE:")
for i in range(1, 4):
    print(i)
else:
    print("Loop finished successfully")

FOR LOOP WITH ELSE:
1
2
3
Loop finished successfully


# *Infinite Loop (Controlled)*

In [53]:
print("CONTROLLED INFINITE LOOP:")
i = 1
while True:
    print(i)
    if i == 3:
        break
    i += 1

CONTROLLED INFINITE LOOP:
1
2
3


# **FUNCTIONS IN PYTHON**

A function is a reusable block of code that performs a specific task and runs when it is called.

# *Simple Function (No Arguments, No Return)*

In [58]:
def greet():
    print("Hello Python")

greet()

Hello Python


# *Built-in Function*

In [84]:
numbers = [1, 2, 3, 4]
print(len(numbers))

4


# *User-Defined Function*

In [86]:
def multiply(a, b):
    return a * b

print(multiply(4, 3))

12


# *Recursive Function*

In [88]:
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n-1)

print(factorial(5))

120


# *Function with Arguments*

In [61]:
def add(a, b):
    print("Sum =", a + b)

add(5, 3)

Sum = 8


# *Function with Return Value*

In [64]:
def square(num):
    return num * num

result = square(4)
print(result)

16


# *Function with Default Argument*

In [67]:
def welcome(name="User"):
    print("Welcome", name)

welcome()
welcome("Amoou")

Welcome User
Welcome Amoou


# *Function with Keyword Arguments*

In [69]:
def student(name, age):
    print(name, age)

student(age=20, name="Ali")

Ali 20


# *Function with Variable-Length Arguments*

In [77]:
def total(*numbers):
    print(sum(numbers))

total(1, 2, 3, 4)

10


# *Function with Variable-Length Keyword Arguments*

In [80]:
def info(**data):
    print(data)

info(name="Ali", age=21)

{'name': 'Ali', 'age': 21}


# **LISTS IN PYTHON**

A list is an ordered, changeable collection in Python that can store multiple items of different data types.

# *append()*

In [93]:
nums = [1, 2, 3]
nums.append(4)
print(nums)

[1, 2, 3, 4]


# *extend()*

In [96]:
nums = [1, 2]
nums.extend([3, 4])
print(nums)

[1, 2, 3, 4]


# *insert()*

In [99]:
nums = [10, 20, 30]
nums.insert(1, 15)
print(nums)

[10, 15, 20, 30]


# *remove()*

In [102]:
nums = [1, 2, 3, 2]
nums.remove(2)
print(nums)

[1, 3, 2]


# *pop()*

In [105]:
nums = [10, 20, 30]
nums.pop()
print(nums)

[10, 20]


# *clear()*

In [108]:
nums = [1, 2, 3]
nums.clear()
print(nums)

[]


# *index()*

In [111]:
nums = [5, 10, 15]
print(nums.index(10))

1


# *count()*

In [114]:
nums = [1, 2, 2, 3]
print(nums.count(2))

2


# *sort()*

In [117]:
nums = [4, 1, 3, 2]
nums.sort()
print(nums)

[1, 2, 3, 4]


# *reverse()*

In [120]:
nums = [1, 2, 3]
nums.reverse()
print(nums)

[3, 2, 1]


# *copy()*

In [123]:
a = [1, 2, 3]
b = a.copy()
print(b)

[1, 2, 3]


# *len()*

In [126]:
nums = [10, 20, 30]
print(len(nums))

3


# **DICTIONARIES IN PYTHON**

A dictionary is a collection of data stored as key–value pairs, where each key is unique.

In [ ]:
student = {"name": "Ali", "age": 20, "marks": 85}
print(student)

# *Access Values*

In [ ]:
print(student["name"])

# *List ➝ Dictionary (using zip)*

In [ ]:
keys = ["name", "age", "grade"]
values = ["Sara", 18, "A"]

data = dict(zip(keys, values))
print(data)

# *List of Tuples ➝ Dictionary*

In [ ]:
items = [("a", 1), ("b", 2), ("c", 3)]
d = dict(items)
print(d)

# *Dictionary ➝ List (Keys)*

In [ ]:
print(list(student.keys()))

# *Dictionary ➝ List (Values)*

In [ ]:
print(list(student.values()))

# *Dictionary ➝ List (Key–Value Tuples)*

In [ ]:
print(list(student.items()))

# *Tuple ➝ Dictionary*

In [ ]:
t = (("x", 10), ("y", 20))
d = dict(t)
print(d)

# *Add / Update Item*

In [ ]:
student["city"] = "Lahore"
print(student)

# *Remove Item (pop)*

In [ ]:
student.pop("age")
print(student)

# *get() Method*

In [ ]:
print(student.get("marks"))

# *Loop Through Dictionary*

In [ ]:
for key, value in student.items():
    print(key, ":", value)

# **2. NUMPY**

NumPy is a Python library used for creating and efficiently manipulating numerical arrays and performing vectorized computations.

In [141]:
import numpy as np

# *Arrays*

An array is a data structure that stores multiple values of the same type in a single variable, allowing fast mathematical operations.

In [144]:
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

Original Array: [10 20 30 40 50]


# *Vectorized Operations*

Vectorized operation means:
No loops, Faster execution, Operations applied to entire array at once

# *Without vectorization (slow)*

In [159]:
result = []
for i in a:
    result.append(i * 2)

# *With vectorization (fast)*

In [161]:
print(a * 2)

[1, 2, 3, 1, 2, 3]


# **3. EXTENDED NUMPY OPERATIONS**

# *Matrix Multiplication*

Matrix multiplication is the operation of multiplying rows of the first matrix with columns of the second matrix using NumPy’s dot() or @ operator.

In [165]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [167]:
result = A @ B 

In [169]:
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result:
 [[19 22]
 [43 50]]


# *Broadcasting*

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array.

In [175]:
result = A + B

In [177]:
print("Array A:\n", A)
print("Array B:\n", B)
print("Result after Broadcasting:\n", result)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Result after Broadcasting:
 [[ 6  8]
 [10 12]]
